/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      "colors": {
              "on-tertiary-container": "#ffd2be",
              "on-secondary-fixed-variant": "#005236",
              "secondary-container": "#6cf8bb",
              "primary-container": "#4f46e5",
              "primary-fixed": "#e2dfff",
              "tertiary": "#7e3000",
              "on-tertiary-fixed": "#351000",
              "on-primary-fixed": "#0f0069",
              "on-surface-variant": "#464555",
              "surface-container-highest": "#e4e1ee",
              "tertiary-fixed": "#ffdbcc",
              "on-tertiary-fixed-variant": "#7b2f00",
              "on-secondary": "#ffffff",
              "on-background": "#1b1b24",
              "surface-dim": "#dcd8e5",
              "surface-container-low": "#f5f2ff",
              "on-error-container": "#93000a",
              "inverse-on-surface": "#f3effc",
              "primary": "#3525cd",
              "surface": "#fcf8ff",
              "secondary-fixed-dim": "#4edea3",
              "on-error": "#ffffff",
              "surface-bright": "#fcf8ff",
              "surface-container-high": "#eae6f4",
              "error": "#ba1a1a",
              "secondary-fixed": "#6ffbbe",
              "primary-fixed-dim": "#c3c0ff",
              "on-secondary-container": "#00714d",
              "inverse-primary": "#c3c0ff",
              "on-primary-container": "#dad7ff",
              "on-primary-fixed-variant": "#3323cc",
              "surface-container-lowest": "#ffffff",
              "on-tertiary": "#ffffff",
              "tertiary-fixed-dim": "#ffb695",
              "surface-variant": "#e4e1ee",
              "error-container": "#ffdad6",
              "inverse-surface": "#302f39",
              "secondary": "#006c49",
              "surface-tint": "#4d44e3",
              "outline": "#777587",
              "surface-container": "#f0ecf9",
              "tertiary-container": "#a44100",
              "on-surface": "#1b1b24",
              "background": "#fcf8ff",
              "on-secondary-fixed": "#002113",
              "on-primary": "#ffffff",
              "outline-variant": "#c7c4d8"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "md": "1rem",
              "base": "4px",
              "margin-desktop": "2.5rem",
              "sm": "0.5rem",
              "xl": "2rem",
              "margin-mobile": "1rem",
              "2xl": "3rem",
              "xs": "0.25rem",
              "lg": "1.5rem",
              "gutter": "1.5rem"
      },
      "fontFamily": {
              "headline-md": ["Inter", "sans-serif"],
              "headline-lg-mobile": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "title-md": ["Inter", "sans-serif"],
              "label-sm": ["Inter", "sans-serif"],
              "display-lg": ["Inter", "sans-serif"],
              "label-md": ["Inter", "sans-serif"],
              "headline-lg": ["Inter", "sans-serif"],
              "title-lg": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"]
      },
      "fontSize": {
              "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
              "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
              "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
              "title-md": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
              "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.03em", "fontWeight": "600" }],
              "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
              "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
              "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
              "body-lg": ["16px", { "lineHeight": "26px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
