name: My First Pipeline

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Step 1: Installing project"

      - run: echo "Step 2: Running tests"

       - run: echo "Step 3: Building project"

       - run: echo "Step 4: Deployment completed"
